/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.livro.CadastrarLivro;
import view.subarea.CadastrarSubarea;
import view.autor.CadastrarAutor;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.PrintWriter;
import java.net.URL;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.derby.impl.drda.NetworkServerControlImpl;
import tools.DAOBaseJDBC;
import tools.SystemDatabase;
import view.autor.ListarAutores;
import view.livro.ListarLivros;
import view.subarea.ListarSubareas;

/**
 *
 * @author Bruno
 */
public class menuPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        // coloca uma figura na barra de título da janela
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/view/img/logo.png")));
        
        //maximiza
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        SystemDatabase systemDB = new SystemDatabase();
        systemDB.createTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        panel_principal = new javax.swing.JDesktopPane();
        panel_superior = new javax.swing.JTabbedPane();
        panel_favoritos = new javax.swing.JPanel();
        btn_cadastrar_livro_fav = new javax.swing.JButton();
        btn_listar_livros_fav = new javax.swing.JButton();
        btn_listar_autores_fav = new javax.swing.JButton();
        panel_cadastros = new javax.swing.JPanel();
        btn_cadastrar_autor_cad = new javax.swing.JButton();
        btn_cadastrar_subarea_cad = new javax.swing.JButton();
        btn_cadastrar_livro_cadastros = new javax.swing.JButton();
        panel_relatorios = new javax.swing.JPanel();
        btn_listar_livros_rel = new javax.swing.JButton();
        btn_listar_autores_rel = new javax.swing.JButton();
        brn_listar_subareas_rel = new javax.swing.JButton();
        panel_inferior = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Biblioteca Passionista");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_principal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        panel_superior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panel_favoritos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        btn_cadastrar_livro_fav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/notebook.png"))); // NOI18N
        btn_cadastrar_livro_fav.setText("Cadastrar Livro");
        btn_cadastrar_livro_fav.setToolTipText("Cadastrar livro");
        btn_cadastrar_livro_fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_livro_favActionPerformed(evt);
            }
        });
        panel_favoritos.add(btn_cadastrar_livro_fav);

        btn_listar_livros_fav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/library.png"))); // NOI18N
        btn_listar_livros_fav.setText("Listar Livros");
        btn_listar_livros_fav.setToolTipText("Listar Livros");
        btn_listar_livros_fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_livros_favActionPerformed(evt);
            }
        });
        panel_favoritos.add(btn_listar_livros_fav);

        btn_listar_autores_fav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/worker.png"))); // NOI18N
        btn_listar_autores_fav.setText("Listar Autores");
        btn_listar_autores_fav.setToolTipText("Listar Autores");
        btn_listar_autores_fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_autores_favActionPerformed(evt);
            }
        });
        panel_favoritos.add(btn_listar_autores_fav);

        panel_superior.addTab("Favoritos", panel_favoritos);

        panel_cadastros.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        btn_cadastrar_autor_cad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/add-user.png"))); // NOI18N
        btn_cadastrar_autor_cad.setText("Cadastrar Autor");
        btn_cadastrar_autor_cad.setToolTipText("Cadastrar Autor");
        btn_cadastrar_autor_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_autor_cadActionPerformed(evt);
            }
        });
        panel_cadastros.add(btn_cadastrar_autor_cad);

        btn_cadastrar_subarea_cad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/clipboard.png"))); // NOI18N
        btn_cadastrar_subarea_cad.setText("Cadastrar Subárea");
        btn_cadastrar_subarea_cad.setToolTipText("Cadastrar Subárea");
        btn_cadastrar_subarea_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_subarea_cadActionPerformed(evt);
            }
        });
        panel_cadastros.add(btn_cadastrar_subarea_cad);

        btn_cadastrar_livro_cadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/notebook.png"))); // NOI18N
        btn_cadastrar_livro_cadastros.setText("Cadastrar Livro");
        btn_cadastrar_livro_cadastros.setToolTipText("Cadastrar livro");
        btn_cadastrar_livro_cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_livro_cadastrosActionPerformed(evt);
            }
        });
        panel_cadastros.add(btn_cadastrar_livro_cadastros);

        panel_superior.addTab("Cadastros", panel_cadastros);

        panel_relatorios.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5));

        btn_listar_livros_rel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/book.png"))); // NOI18N
        btn_listar_livros_rel.setText("Listar Livros");
        btn_listar_livros_rel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_livros_relActionPerformed(evt);
            }
        });
        panel_relatorios.add(btn_listar_livros_rel);

        btn_listar_autores_rel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/worker.png"))); // NOI18N
        btn_listar_autores_rel.setText("Listar Autores");
        btn_listar_autores_rel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listar_autores_relActionPerformed(evt);
            }
        });
        panel_relatorios.add(btn_listar_autores_rel);

        brn_listar_subareas_rel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/job-search.png"))); // NOI18N
        brn_listar_subareas_rel.setText("Listar Subáreas");
        brn_listar_subareas_rel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_listar_subareas_relActionPerformed(evt);
            }
        });
        panel_relatorios.add(brn_listar_subareas_rel);

        panel_superior.addTab("Relatórios", panel_relatorios);

        panel_inferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panel_inferiorLayout = new javax.swing.GroupLayout(panel_inferior);
        panel_inferior.setLayout(panel_inferiorLayout);
        panel_inferiorLayout.setHorizontalGroup(
            panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_inferiorLayout.setVerticalGroup(
            panel_inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_inferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_superior)
            .addComponent(panel_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_principal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_livro_favActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_livro_favActionPerformed
        CadastrarLivro cad_livro = new CadastrarLivro();
        this.setInternalDesktop(cad_livro);
    }//GEN-LAST:event_btn_cadastrar_livro_favActionPerformed

    private void btn_cadastrar_autor_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_autor_cadActionPerformed
        CadastrarAutor cad_autor = new CadastrarAutor();
        this.setInternalDesktop(cad_autor);
    }//GEN-LAST:event_btn_cadastrar_autor_cadActionPerformed

    private void btn_cadastrar_livro_cadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_livro_cadastrosActionPerformed
        CadastrarLivro cad_livro = new CadastrarLivro();
        this.setInternalDesktop(cad_livro);
    }//GEN-LAST:event_btn_cadastrar_livro_cadastrosActionPerformed

    private void btn_cadastrar_subarea_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_subarea_cadActionPerformed
        CadastrarSubarea cad_subarea = new CadastrarSubarea();
        this.setInternalDesktop(cad_subarea);
    }//GEN-LAST:event_btn_cadastrar_subarea_cadActionPerformed

    private void btn_listar_autores_relActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_autores_relActionPerformed
        ListarAutores buscarAutor = new ListarAutores();
        this.setInternalDesktop(buscarAutor);
    }//GEN-LAST:event_btn_listar_autores_relActionPerformed

    private void btn_listar_autores_favActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_autores_favActionPerformed
        ListarAutores buscarAutor = new ListarAutores();
        this.setInternalDesktop(buscarAutor);
    }//GEN-LAST:event_btn_listar_autores_favActionPerformed

    private void brn_listar_subareas_relActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_listar_subareas_relActionPerformed
        ListarSubareas listarSubareas = new ListarSubareas();
        this.setInternalDesktop(listarSubareas);
    }//GEN-LAST:event_brn_listar_subareas_relActionPerformed

    private void btn_listar_livros_relActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_livros_relActionPerformed
        ListarLivros listarLivros = new ListarLivros();
        this.setInternalDesktop(listarLivros);
    }//GEN-LAST:event_btn_listar_livros_relActionPerformed

    private void btn_listar_livros_favActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listar_livros_favActionPerformed
        ListarLivros listarLivros = new ListarLivros();
        this.setInternalDesktop(listarLivros);
    }//GEN-LAST:event_btn_listar_livros_favActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente fechar o programa?", "Mensagem de saída",JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            DAOBaseJDBC.closeConn();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing
    
    private void setInternalDesktop(Object componente){
        Component c = (Component) componente;
        this.panel_principal.add(c);
        c.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_listar_subareas_rel;
    private javax.swing.JButton btn_cadastrar_autor_cad;
    private javax.swing.JButton btn_cadastrar_livro_cadastros;
    private javax.swing.JButton btn_cadastrar_livro_fav;
    private javax.swing.JButton btn_cadastrar_subarea_cad;
    private javax.swing.JButton btn_listar_autores_fav;
    private javax.swing.JButton btn_listar_autores_rel;
    private javax.swing.JButton btn_listar_livros_fav;
    private javax.swing.JButton btn_listar_livros_rel;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel panel_cadastros;
    private javax.swing.JPanel panel_favoritos;
    private javax.swing.JPanel panel_inferior;
    private javax.swing.JDesktopPane panel_principal;
    private javax.swing.JPanel panel_relatorios;
    private javax.swing.JTabbedPane panel_superior;
    // End of variables declaration//GEN-END:variables

}
