/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.subarea;

import controller.SubareaController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import model.Subarea;

/**
 *
 * @author Bruno
 */
public class CadastrarSubarea extends javax.swing.JInternalFrame {
    SubareaController subareaController = new SubareaController();
    /**
     * Creates new form CadastrarAutor
     */
    public CadastrarSubarea() {
        initComponents();
        getRootPane().setDefaultButton(btn_confirmar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        panel_principal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_dados = new javax.swing.JPanel();
        label_nome_subarea = new javax.swing.JLabel();
        input_nome_subarea = new javax.swing.JTextField();
        label_codigo_subarea = new javax.swing.JLabel();
        input_codigo_subarea = new javax.swing.JTextField();
        panel_botoes = new javax.swing.JPanel();
        btn_confirmar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar subárea");
        setToolTipText("Cadastrar subárea");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/diagram.png"))); // NOI18N
        jPanel1.add(jLabel1);

        panel_dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar subárea"));
        panel_dados.setToolTipText("Cadastrar subárea");
        panel_dados.setLayout(new java.awt.GridLayout(2, 2, 0, 10));

        label_nome_subarea.setText("Nome da subárea:");
        panel_dados.add(label_nome_subarea);
        panel_dados.add(input_nome_subarea);

        label_codigo_subarea.setText("Código da subárea:");
        panel_dados.add(label_codigo_subarea);

        input_codigo_subarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_codigo_subareaActionPerformed(evt);
            }
        });
        panel_dados.add(input_codigo_subarea);

        panel_botoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        panel_botoes.setLayout(flowLayout1);

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });
        panel_botoes.add(btn_confirmar);

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        panel_botoes.add(btn_voltar);

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_dados, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_botoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_codigo_subareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_codigo_subareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_codigo_subareaActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        try {
            if(this.validarCampos()){
                this.validarCodigo();
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja salvar nova subárea?", "Confirmação.", JOptionPane.INFORMATION_MESSAGE);
                if (opcao == JOptionPane.YES_OPTION){                    
                    if(this.salvarSubarea() == true){
                        JOptionPane.showMessageDialog(null, "Subarea salvo com sucesso!", "Sucesso.", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    }
                }
            }
        }  catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro de validação.", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_confirmarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField input_codigo_subarea;
    private javax.swing.JTextField input_nome_subarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel label_codigo_subarea;
    private javax.swing.JLabel label_nome_subarea;
    private javax.swing.JPanel panel_botoes;
    private javax.swing.JPanel panel_dados;
    private javax.swing.JPanel panel_principal;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() throws Exception {
            this.validarNome();
            //this.validarCodigo();
            return true;
    }

    private boolean validarNome() throws Exception {
        if (this.input_nome_subarea.getText().isEmpty() == true){
            this.input_nome_subarea.setBorder(new LineBorder(Color.RED));
            throw new Exception("Nome da subárea não pode ser vazia.");
        }
        return true;
    }

    private void validarCodigo() throws Exception {
        String codigo = this.input_codigo_subarea.getText();
        if (codigo.isEmpty() == true){
            this.input_codigo_subarea.setBorder(new LineBorder(Color.RED));
            throw new Exception("Código da subárea não pode ser vazia.");
        }
        if (subareaController.verificarCodigoExistente(codigo) == true){
            throw new Exception("Código já cadastrado na base de dados.");
        }
    }

    private boolean salvarSubarea() {
        Subarea subarea = new Subarea(this.input_codigo_subarea.getText(), this.input_nome_subarea.getText());
        try {
            subareaController.salvarSubarea(subarea);
            return true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro.", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
}
