/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.autor;

import controller.AutorController;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Autor;

/**
 *
 * @author Bruno
 */
public class BuscarAutor extends javax.swing.JDialog{
    AutorController autorController = new AutorController();
    Autor autor = null;
    boolean statusAtivo = true;
    DefaultTableModel dtm;
    /**
     * Creates new form BuscarAutor
     */
    public BuscarAutor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(btn_pesquisar);
    }

    public BuscarAutor() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btn_pesquisar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_pesquisa = new javax.swing.JPanel();
        label_pesquisar_nome = new javax.swing.JLabel();
        input_pesquisar = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        panel_tabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_autores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_confirmar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar autor");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel_pesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_pesquisa.setLayout(new javax.swing.BoxLayout(panel_pesquisa, javax.swing.BoxLayout.LINE_AXIS));

        label_pesquisar_nome.setText("Nome do autor:");
        panel_pesquisa.add(label_pesquisar_nome);

        input_pesquisar.setPreferredSize(new java.awt.Dimension(400, 20));
        panel_pesquisa.add(input_pesquisar);

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.setToolTipText("");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });
        panel_pesquisa.add(btn_pesquisar);

        panel_tabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Autores encontrados"));

        table_autores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_autores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Email", "Site", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_autores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_autores);
        if (table_autores.getColumnModel().getColumnCount() > 0) {
            table_autores.getColumnModel().getColumn(0).setPreferredWidth(120);
            table_autores.getColumnModel().getColumn(0).setMaxWidth(120);
            table_autores.getColumnModel().getColumn(4).setMinWidth(0);
            table_autores.getColumnModel().getColumn(4).setPreferredWidth(0);
            table_autores.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        javax.swing.GroupLayout panel_tabelaLayout = new javax.swing.GroupLayout(panel_tabela);
        panel_tabela.setLayout(panel_tabelaLayout);
        panel_tabelaLayout.setHorizontalGroup(
            panel_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panel_tabelaLayout.setVerticalGroup(
            panel_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_confirmar);

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_voltar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
            .addComponent(panel_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        List<Autor> autoresEncontrados;
        try {
            autoresEncontrados = this.buscarAutor(input_pesquisar.getText());
            this.montarTabela(autoresEncontrados);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Nenhum autor encontrado com esse nome.", "Autor não encontrado.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        this.statusAtivo = false;
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.statusAtivo = false;
    }//GEN-LAST:event_formWindowClosing

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        try{
            this.autor = (Autor)table_autores.getValueAt(table_autores.getSelectedRow(), 4);
            if (this.autor == null){
                throw new Exception();
            }
            this.dispose();
            this.statusAtivo = false;
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Nenhum autor selecionado!", "Erro.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_confirmarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarAutor dialog = new BuscarAutor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JTextField input_pesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_pesquisar_nome;
    private javax.swing.JPanel panel_pesquisa;
    private javax.swing.JPanel panel_tabela;
    private javax.swing.JTable table_autores;
    // End of variables declaration//GEN-END:variables
    
    public Autor getAutor(){
        return this.autor;
    }
    
    public boolean getStatusAtivo(){
        return this.statusAtivo;
    }
    
    private List<Autor> buscarAutor(String nomeAutor) throws Exception {
        return this.autorController.recuperarAutoresSemPaginacao(nomeAutor);
    }

    private void montarTabela(List<Autor> autoresEncontrados) {
        this.dtm = (DefaultTableModel) table_autores.getModel();
        this.limparTabela(dtm);
        for (Autor a : autoresEncontrados){
            this.dtm.addRow(new Object[]{a.getId_autor(), a.getNome_autor(), a.getEmail_autor(),
                a.getSite_autor(), a});
        }
    }
    
    private void limparTabela(DefaultTableModel dtm) {
        while (dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
    }
}
